### ISSUE TITLE
remove from active-repos?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/smorgasbord#3]
In light of #1 (repo has been broken since Oct 2013), can this repo be removed from chipper/data/active-repos?

**Comment by samreid** [comment]
Can we just delete smorgasbord?  #5

**Comment by pixelzoom** [comment]
Deleting would be fine too.  Unless we have some need to explore the possibility of "mixing and matching tabs from different PhET simulations" (as noted in README.md).

**Comment by samreid** [comment]
I haven't heard that raised as a requested feature recently, but perhaps we should double check with @kathy-phet before deleting.  We always have the alternate options of:
a) using iframes or separate webpages to get to the content of multiple sims
b) creating a custom sim that combines the two sub-sims as necessary.

**Comment by samreid** [comment]
After reviewing smorgasbord, in my opinion, it is a half-baked prototype that does not solve significant problems that we currently have.  If we want to move toward a "build sims with screens from any other sims" we will likely need to start from scratch.  Assigned to developer-meeting to discuss and see if we should delete.

**Comment by pixelzoom** [comment]
+1 to delete.

**Comment by pixelzoom** [comment]
8/20/15 dev meeting consensus: Yes.

**Comment by samreid** [comment]
I'll close this issue before deleting, just to get closure :smile_cat:
